#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

layout (std430, binding = 0) readonly   buffer AsIn     {   uint as[];  };
layout (std430, binding = 1) readonly   buffer BsIn     {   uint bs[];  };
layout (std430, binding = 2) writeonly  buffer CsOut    {   uint cs[];  };

layout (push_constant) uniform PushConstants {
    uint width;
    uint height;
} params;

layout (local_size_x = 16, local_size_y = 16) in;
void main()
{
    const uint i = gl_GlobalInvocationID.y * params.width + gl_GlobalInvocationID.x;

    rassert(as[i] == 3 * (i + 5) + 7, 435234223);
    rassert(bs[i] == 11 * (i + 13) + 17, 435432367);

    cs[i] = as[i] + bs[i];
}
