#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

layout (std430, binding = 0) readonly	buffer AsIn		{	uint as[];	};
layout (std430, binding = 1) readonly	buffer BsIn		{	uint bs[];	};
layout (std430, binding = 2) writeonly	buffer CsOut	{	uint cs[];	};

layout (push_constant) uniform PushConstants {
	uint width;
    uint height;
} params;

layout (local_size_x = 1, local_size_y = 256) in;
void main()
{
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;
    uint curr_y;
    if ((y & 1u) == 0) {
        curr_y = y / 2;
    } else {
        curr_y = params.height - 1 - y / 2;
    }

    uint i = params.width * curr_y + x;
    if (i >= params.width * params.height) {
        return;
    }

    rassert(as[i] == 3 * (i + 5) + 7, 435234223);
    rassert(bs[i] == 11 * (i + 13) + 17, 435432367);

    cs[i] = as[i] + bs[i];
}
