#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

layout (std430, binding = 0) readonly buffer MatrixIn   { float matrix[];            };
layout (std430, binding = 1)          buffer MatrixOut  { float transposed_matrix[]; };

layout (push_constant) uniform PushConstants {
    uint w;
    uint h;
} params;

shared float local_memory[GROUP_SIZE];

uint sharedIndex(uint row, uint col)
{
    return row * GROUP_SIZE_X + ((col + row) % GROUP_SIZE_X);
}

layout (local_size_x = GROUP_SIZE_X, local_size_y = GROUP_SIZE_Y) in;
void main()
{
    uint lx = gl_LocalInvocationID.x;
    uint ly = gl_LocalInvocationID.y;

    uint x = gl_WorkGroupID.x * GROUP_SIZE_X + lx;
    uint y = gl_WorkGroupID.y * GROUP_SIZE_Y + ly;

    if (x < params.w && y < params.h)
        local_memory[sharedIndex(ly, lx)] = matrix[y * params.w + x];

    barrier();

    uint outX = gl_WorkGroupID.y * GROUP_SIZE_Y + lx;
    uint outY = gl_WorkGroupID.x * GROUP_SIZE_X + ly;

    if (outX < params.h && outY < params.w) {
        transposed_matrix[outY * params.h + outX] = local_memory[sharedIndex(lx, ly)];
    }
}
