#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

#extension GL_EXT_control_flow_attributes : require

layout (std430, binding = 0) readonly buffer MatrixAIn   { float a[]; }; // rows=h x cols=k
layout (std430, binding = 1) readonly buffer MatrixBIn   { float b[]; }; // rows=k x cols=w
layout (std430, binding = 2)          buffer MatrixCOut  { float c[]; }; // rows=h x cols=w

layout (push_constant) uniform PushConstants {
    uint w;
    uint h;
    uint k;
} params;

shared float part_a[GROUP_SIZE_XY][GROUP_SIZE_XY];
shared float part_b[GROUP_SIZE_XY][GROUP_SIZE_XY * 2];

layout (local_size_x = GROUP_SIZE_XY, local_size_y = GROUP_SIZE_XY) in;
void main()
{
    const uint local_i = gl_LocalInvocationID.x;
    const uint local_j = gl_LocalInvocationID.y;

    const uint j = gl_GlobalInvocationID.y;
    const uint i0 = gl_WorkGroupID.x * GROUP_SIZE_XY * 2 + local_i;
    const uint i1 = i0 + GROUP_SIZE_XY;

    float sum0 = 0;
    float sum1 = 0;
    for (uint step = 0; step < params.k; step += GROUP_SIZE_XY) {
        part_a[local_j][local_i] = (step + local_i < params.k && j < params.h)
                                        ? a[j * params.k + step + local_i]
                                        : 0;

        part_b[local_j][local_i] = (step + local_j < params.k && i0 < params.w)
                                        ? b[i0 + params.w * (step + local_j)]
                                        : 0;
        part_b[local_j][local_i + GROUP_SIZE_XY] = (step + local_j < params.k && i1 < params.w)
                                                        ? b[i1 + params.w * (step + local_j)]
                                                        : 0;

        barrier();

        [[unroll]]
        for (uint l = 0; l < GROUP_SIZE_XY; ++l) {
            const float pa = part_a[local_j][l];
            sum0 += pa * part_b[l][local_i];
            sum1 += pa * part_b[l][local_i + GROUP_SIZE_XY];
        }

        barrier();
    }

    if (i0 < params.w && j < params.h) {
        c[j * params.w + i0] = sum0;
    }
    if (i1 < params.w && j < params.h) {
        c[j * params.w + i1] = sum1;
    }
}
