#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

layout (std430, binding = 0) readonly buffer MatrixIn   { float matrix[];            };
layout (std430, binding = 1)          buffer MatrixOut  { float transposed_matrix[]; };

layout (push_constant) uniform PushConstants {
    uint w;
    uint h;
} params;

shared float local_buffer[GROUP_SIZE_Y][GROUP_SIZE_X + 1];

layout (local_size_x = GROUP_SIZE_X, local_size_y = GROUP_SIZE_Y) in;
void main()
{
    const uint i = gl_GlobalInvocationID.x;
    const uint j = gl_GlobalInvocationID.y;

    const uint local_i = gl_LocalInvocationID.x;
    const uint local_j = gl_LocalInvocationID.y;

    const uint group_i = gl_WorkGroupID.x;
    const uint group_j = gl_WorkGroupID.y;

    if (i < params.w && j < params.h) {
        local_buffer[local_j][local_i] = matrix[j * params.w + i];
    }

    barrier();

    const uint out_i = group_j * GROUP_SIZE_X + local_i;
    const uint out_j = group_i * GROUP_SIZE_Y + local_j;

    if (out_i < params.h && out_j < params.w) {
        transposed_matrix[out_j * params.h + out_i] = local_buffer[local_i][local_j];
    }
}
