#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

layout (std430, binding = 0) readonly buffer MatrixAIn   { float a[]; }; // rows=h x cols=k
layout (std430, binding = 1) readonly buffer MatrixBIn   { float b[]; }; // rows=k x cols=w
layout (std430, binding = 2)          buffer MatrixCOut  { float c[]; }; // rows=h x cols=w

layout (push_constant) uniform PushConstants {
    uint w;
    uint h;
    uint k;
} params;

shared float part_a[GROUP_SIZE_XY][GROUP_SIZE_XY];
shared float part_b[GROUP_SIZE_XY][GROUP_SIZE_XY];

layout (local_size_x = GROUP_SIZE_XY, local_size_y = GROUP_SIZE_XY) in;
void main()
{
    const uint local_i = gl_LocalInvocationID.x;
    const uint local_j = gl_LocalInvocationID.y;

    const uint i = gl_GlobalInvocationID.x;
    const uint j = gl_GlobalInvocationID.y;

    if (i >= params.w || j >= params.h) {
        return;
    }

    float sum = 0;
    for (uint step = 0; step < params.k; step += GROUP_SIZE_XY) {
        part_a[local_j][local_i] = (step + local_i < params.k && j < params.h)
                                        ? a[j * params.k + step + local_i]
                                        : 0;

        part_b[local_j][local_i] = (step + local_j < params.k && i < params.w)
                                        ? b[i + params.w * (step + local_j)]
                                        : 0;

        barrier();

        for (uint l = 0; l < 16; ++l) {
            sum += part_a[local_j][l] * part_b[l][local_i];
        }

        barrier();
    }

    if (i < params.w && j < params.h) {
        c[j * params.w + i] += sum;
    }
}
