#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

#define WARP_SIZE 32

layout (std430, binding = 0) readonly  buffer AsIn  { uint a[]; };
layout (std430, binding = 1) writeonly buffer BsOut { uint b[]; };

layout (push_constant) uniform PushConstants {
    uint n;
} params;

layout (local_size_x = GROUP_SIZE) in;

shared uint local_data[GROUP_SIZE];

void main()
{
    const uint index = gl_GlobalInvocationID.x;
    const uint local_index = gl_LocalInvocationID.x;

    local_data[local_index] = index < params.n ? a[index] : 0;

    memoryBarrierShared();
    barrier();

    int level = GROUP_SIZE / 2;
    while (level > 0) {
        if (local_index < level) {
            local_data[local_index] += local_data[local_index + level];
        }
        memoryBarrierShared();
        barrier();
        level /= 2;
    }

    if (local_index == 0) {
        b[gl_WorkGroupID.x] = local_data[0];
    }
}
