#version 450

#include <libgpu/vulkan/vk/common.vk>

#include "../defines.h"

#define WARP_SIZE 32

layout (std430, binding = 0) readonly  buffer AsIn  { uint a[]; };
layout (std430, binding = 1) writeonly buffer BsOut { uint b[]; };

layout (push_constant) uniform PushConstants {
    uint n;
} params;

layout (local_size_x = GROUP_SIZE) in;

shared uint local_data[GROUP_SIZE];

void main()
{
    // Подсказки:
    const uint index = gl_GlobalInvocationID.x;
    const uint local_index = gl_LocalInvocationID.x;

    if (index >= params.n) {
        local_data[local_index] = 0;
    } else {
        local_data[local_index] = a[index];
    }

    barrier();

    uint curr_size = GROUP_SIZE;
    while (curr_size > 1u) {
        curr_size /= 2u;
        if (local_index < curr_size) {
            local_data[local_index] += local_data[local_index + curr_size];
        }

        barrier();
    }

    if (local_index == 0u) {
        b[gl_WorkGroupID.x] = local_data[0];
    }
}